import { render, screen } from '@testing-library/react';
import Trend from '../Trend';

test('renders trend description', () => {
  const repo = {
    allow_forking: true,
    archive_url: "https://api.github.com/repos/rickwierenga/sci-hub-injector/{archive_format}{/ref}",
    archived: false,
    assignees_url: "https://api.github.com/repos/rickwierenga/sci-hub-injector/assignees{/user}",
    blobs_url: "https://api.github.com/repos/rickwierenga/sci-hub-injector/git/blobs{/sha}",
    branches_url: "https://api.github.com/repos/rickwierenga/sci-hub-injector/branches{/branch}",
    clone_url: "https://github.com/rickwierenga/sci-hub-injector.git",
    collaborators_url: "https://api.github.com/repos/rickwierenga/sci-hub-injector/collaborators{/collaborator}",
    comments_url: "https://api.github.com/repos/rickwierenga/sci-hub-injector/comments{/number}",
    commits_url: "https://api.github.com/repos/rickwierenga/sci-hub-injector/commits{/sha}",
    compare_url: "https://api.github.com/repos/rickwierenga/sci-hub-injector/compare/{base}...{head}",
    contents_url: "https://api.github.com/repos/rickwierenga/sci-hub-injector/contents/{+path}",
    contributors_url: "https://api.github.com/repos/rickwierenga/sci-hub-injector/contributors",
    created_at: "2022-01-14T16:17:19Z",
    default_branch: "main",
    deployments_url: "https://api.github.com/repos/rickwierenga/sci-hub-injector/deployments",
    description: "Adds SciHub links to popular publisher websites",
    disabled: false,
    downloads_url: "https://api.github.com/repos/rickwierenga/sci-hub-injector/downloads",
    events_url: "https://api.github.com/repos/rickwierenga/sci-hub-injector/events",
    fork: false,
    forks: 37,
    forks_count: 37,
    forks_url: "https://api.github.com/repos/rickwierenga/sci-hub-injector/forks",
    full_name: "rickwierenga/sci-hub-injector",
    git_commits_url: "https://api.github.com/repos/rickwierenga/sci-hub-injector/git/commits{/sha}",
    git_refs_url: "https://api.github.com/repos/rickwierenga/sci-hub-injector/git/refs{/sha}",
    git_tags_url: "https://api.github.com/repos/rickwierenga/sci-hub-injector/git/tags{/sha}",
    git_url: "git://github.com/rickwierenga/sci-hub-injector.git",
    has_downloads: true,
    has_issues: true,
    has_pages: false,
    has_projects: true,
    has_wiki: true,
    homepage: null,
    hooks_url: "https://api.github.com/repos/rickwierenga/sci-hub-injector/hooks",
    html_url: "https://github.com/rickwierenga/sci-hub-injector",
    id: 448030501,
    is_template: false,
    issue_comment_url: "https://api.github.com/repos/rickwierenga/sci-hub-injector/issues/comments{/number}",
    issue_events_url: "https://api.github.com/repos/rickwierenga/sci-hub-injector/issues/events{/number}",
    issues_url: "https://api.github.com/repos/rickwierenga/sci-hub-injector/issues{/number}",
    keys_url: "https://api.github.com/repos/rickwierenga/sci-hub-injector/keys{/key_id}",
    labels_url: "https://api.github.com/repos/rickwierenga/sci-hub-injector/labels{/name}",
    language: null,
    languages_url: "https://api.github.com/repos/rickwierenga/sci-hub-injector/languages",
    license: {key: "gpl-3.0", name: "GNU General Public License v3.0", spdx_id: "GPL-3.0"},
    merges_url: "https://api.github.com/repos/rickwierenga/sci-hub-injector/merges",
    milestones_url: "https://api.github.com/repos/rickwierenga/sci-hub-injector/milestones{/number}",
    mirror_url: null,
    name: "sci-hub-injector",
    node_id: "R_kgDOGrRnJQ",
    notifications_url: "https://api.github.com/repos/rickwierenga/sci-hub-injector/notifications{?since,all,participating}",
    open_issues: 8,
    open_issues_count: 8,
    owner: {login: "rickwierenga", id: 36956818, node_id: "MDQ6VXNlcjM2OTU2ODE4"},
    private: false,
    pulls_url: "https://api.github.com/repos/rickwierenga/sci-hub-injector/pulls{/number}",
    pushed_at: "2022-01-18T10:39:55Z",
    releases_url: "https://api.github.com/repos/rickwierenga/sci-hub-injector/releases{/id}",
    score: 1,
    size: 5004,
    ssh_url: "git@github.com:rickwierenga/sci-hub-injector.git",
    stargazers_count: 537,
    stargazers_url: "https://api.github.com/repos/rickwierenga/sci-hub-injector/stargazers",
    statuses_url: "https://api.github.com/repos/rickwierenga/sci-hub-injector/statuses/{sha}",
    subscribers_url: "https://api.github.com/repos/rickwierenga/sci-hub-injector/subscribers",
    subscription_url: "https://api.github.com/repos/rickwierenga/sci-hub-injector/subscription",
    svn_url: "https://github.com/rickwierenga/sci-hub-injector",
    tags_url: "https://api.github.com/repos/rickwierenga/sci-hub-injector/tags",
    teams_url: "https://api.github.com/repos/rickwierenga/sci-hub-injector/teams",
    topics: [],
    trees_url: "https://api.github.com/repos/rickwierenga/sci-hub-injector/git/trees{/sha}",
    updated_at: "2022-01-18T11:15:00Z",
    url: "https://api.github.com/repos/rickwierenga/sci-hub-injector",
    visibility: "public",
    watchers: 537,
    watchers_count: 537,
  }
  
  render(<Trend repo={repo}/>);
  
  const description = screen.getByText(repo.description);
  expect(description).toBeInTheDocument();
});
